# This file was generated by GoReleaser. DO NOT EDIT.
cask "ywiki" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "115507729fc3b4cd4a912b93f273bdb6d61ea4a49042e23fe8ac7902c35b1a9a"
      url "https://github.com/cloud-yyy/ywiki/releases/download/v#{version}/ywiki_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "f5b0db7638c23b7e287078fa8301daa1385d0ea1cb2de65c283420b3022cb1c2"
      url "https://github.com/cloud-yyy/ywiki/releases/download/v#{version}/ywiki_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "833cbec100cc99ce785b4121cd88c1035e48bf13ea1cb662a6413849fb91a500"
      url "https://github.com/cloud-yyy/ywiki/releases/download/v#{version}/ywiki_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "e1241eb2e99a2a268a8a1004d9620c78f1c722872cc9b728e8ed9d3bcc65f103"
      url "https://github.com/cloud-yyy/ywiki/releases/download/v#{version}/ywiki_#{version}_linux_amd64.tar.gz"
    end
  end

  name "ywiki"
  desc "Yandex Wiki CLI for humans and LLM agents"
  homepage "https://github.com/cloud-yyy/ywiki"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ywiki"
  bash_completion "completions/ywiki.bash"
  fish_completion "completions/ywiki.fish"
  zsh_completion "completions/_ywiki"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ywiki"]
  end

  # No zap stanza required
end
