# This file was generated by GoReleaser. DO NOT EDIT.
cask "ywiki" do
  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "338fa3733b92fe904a6b233c10bb522c792044bc622ed8d90769c3fab633cbab"
      url "https://github.com/cloud-yyy/ywiki/releases/download/v#{version}/ywiki_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "b12f17d5ffba4362ed1ca7e6a062e07a0bf7ba005f932509a009cd81762fc2df"
      url "https://github.com/cloud-yyy/ywiki/releases/download/v#{version}/ywiki_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "8758bc125d61f03297c3d820bee51dfe7d731ab1ac903e1a42c74c8be86e6948"
      url "https://github.com/cloud-yyy/ywiki/releases/download/v#{version}/ywiki_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "10a0d27037f138c362d351b6187af4ec4133807505eead409a962e3ace366334"
      url "https://github.com/cloud-yyy/ywiki/releases/download/v#{version}/ywiki_#{version}_linux_amd64.tar.gz"
    end
  end

  name "ywiki"
  desc "Yandex Wiki CLI for humans and LLM agents"
  homepage "https://github.com/cloud-yyy/ywiki"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ywiki"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ywiki"]
  end
  generate_completions_from_executable "ywiki", "completion",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required
end
