# This file was generated by GoReleaser. DO NOT EDIT.
cask "ywiki" do
  version "0.1.2"

  on_macos do
    on_arm do
      sha256 "3a8560cfe36b0b0f3bdf27ec019c30e68409768fb5ef040851d8b6de1f3f5f80"
      url "https://github.com/cloud-yyy/ywiki/releases/download/v#{version}/ywiki_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "4f32e46937e6decb6da03281e35e8e372ef12b7e079534aca6934ff7a77756f4"
      url "https://github.com/cloud-yyy/ywiki/releases/download/v#{version}/ywiki_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "2cc08364716950a02af8303e31548ae4f6733f8d28dd2e8c76a850f59e6c7340"
      url "https://github.com/cloud-yyy/ywiki/releases/download/v#{version}/ywiki_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "975013e164995e3bdcccdea234f30821dccfba103c15176b2cfb453257df53e5"
      url "https://github.com/cloud-yyy/ywiki/releases/download/v#{version}/ywiki_#{version}_linux_amd64.tar.gz"
    end
  end

  name "ywiki"
  desc "Yandex Wiki CLI for humans and LLM agents"
  homepage "https://github.com/cloud-yyy/ywiki"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ywiki"
  bash_completion "completions/ywiki.bash"
  fish_completion "completions/ywiki.fish"
  zsh_completion "completions/_ywiki"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ywiki"]
  end

  # No zap stanza required
end
